version: '3'

services:
  fpm:
    build:
      context: php${PHP_VERSION}/fpm
      args:
        PHP_ENABLE_REDIS: ${PHP_ENABLE_REDIS}
        PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
    image: readymadehost/wordpress-dev-docker-php${PHP_VERSION}-fpm:${DOCKER_TAG}

  cli:
    build:
      context: php${PHP_VERSION}/cli
      args:
        NODE_VERSION: ${NODE_VERSION}
        PHP_ENABLE_REDIS: ${PHP_ENABLE_REDIS}
        PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
    image: readymadehost/wordpress-dev-docker-php${PHP_VERSION}-cli:${DOCKER_TAG}
